name: beer_game_manager_bot
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/riccardocescon/beer_game_manager_bot

environment:
  sdk: ^3.2.3

dependencies:
  dotenv: ^4.2.0
  equatable: ^2.0.5
  intl: ^0.19.0
  teledart: ^0.6.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
