name: beer_game_manager_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  equatable: ^2.0.5
  intl: ^0.19.0
  teledart: ^0.6.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
